<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class postSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $storeId = 4;
        $itemId= 1;
        DB::table('posts')->insert([
            [
                'user_id' => 1,
                'price' => 105,
                'description' => '安いです。',
                'created_at' => '2024-04-01 13:00:00',
                'updated_at' => '2024-04-01 13:00:00',
                'store_id' => $storeId,
                'item_id' => $itemId,
            ],
            [
                'user_id' => 1,
                'price' => 105,
                'description' => '安いです。',
                'created_at' => '2024-04-02 13:00:00',
                'updated_at' => '2024-04-02 13:00:00',
                'store_id' => $storeId,
                'item_id' => $itemId,
            ],
            [
                'user_id' => 1,
                'price' => 105,
                'description' => '安いです。',
                'created_at' => '2024-04-03 13:00:00',
                'updated_at' => '2024-04-03 13:00:00',
                'store_id' => $storeId,
                'item_id' => $itemId,
            ],
            [
                'user_id' => 1,
                'price' => 105,
                'description' => '安いです。',
                'created_at' => '2024-04-04 13:00:00',
                'updated_at' => '2024-04-04 13:00:00',
                'store_id' => $storeId,
                'item_id' => $itemId,
            ],
            [
                'user_id' => 1,
                'price' => 105,
                'description' => '安いです。',
                'created_at' => '2024-04-05 13:00:00',
                'updated_at' => '2024-04-05 13:00:00',
                'store_id' => $storeId,
                'item_id' => $itemId,
            ],
            [
                'user_id' => 1,
                'price' => 105,
                'description' => '安いです。',
                'created_at' => '2024-04-06 13:00:00',
                'updated_at' => '2024-04-06 13:00:00',
                'store_id' => $storeId,
                'item_id' => $itemId,
            ],
            [
                'user_id' => 1,
                'price' => 105,
                'description' => '安いです。',
                'created_at' => '2024-04-07 13:00:00',
                'updated_at' => '2024-04-07 13:00:00',
                'store_id' => $storeId,
                'item_id' => $itemId,
            ],
            [
                'user_id' => 1,
                'price' => 105,
                'description' => '安いです。',
                'created_at' => '2024-04-08 13:00:00',
                'updated_at' => '2024-04-08 13:00:00',
                'store_id' => $storeId,
                'item_id' => $itemId,
            ],
            [
                'user_id' => 1,
                'price' => 105,
                'description' => '安いです。',
                'created_at' => '2024-04-09 13:00:00',
                'updated_at' => '2024-04-09 13:00:00',
                'store_id' => $storeId,
                'item_id' => $itemId,
            ],
            [
                'user_id' => 1,
                'price' => 105,
                'description' => '安いです。',
                'created_at' => '2024-04-10 13:00:00',
                'updated_at' => '2024-04-10 13:00:00',
                'store_id' => $storeId,
                'item_id' => $itemId,
            ],
            [
                'user_id' => 1,
                'price' => 105,
                'description' => '安いです。',
                'created_at' => '2024-04-11 13:00:00',
                'updated_at' => '2024-04-11 13:00:00',
                'store_id' => $storeId,
                'item_id' => $itemId,
            ],
            [
                'user_id' => 1,
                'price' => 105,
                'description' => '安いです。',
                'created_at' => '2024-04-12 13:00:00',
                'updated_at' => '2024-04-12 13:00:00',
                'store_id' => $storeId,
                'item_id' => $itemId,
            ],
            [
                'user_id' => 1,
                'price' => 105,
                'description' => '安いです。',
                'created_at' => '2024-04-13 13:00:00',
                'updated_at' => '2024-04-13 13:00:00',
                'store_id' => $storeId,
                'item_id' => $itemId,
            ],
            [
                'user_id' => 1,
                'price' => 105,
                'description' => '安いです。',
                'created_at' => '2024-04-14 13:00:00',
                'updated_at' => '2024-04-14 13:00:00',
                'store_id' => $storeId,
                'item_id' => $itemId,
            ],
            [
                'user_id' => 1,
                'price' => 105,
                'description' => '安いです。',
                'created_at' => '2024-04-15 13:00:00',
                'updated_at' => '2024-04-15 13:00:00',
                'store_id' => $storeId,
                'item_id' => $itemId,
            ],
            [
                'user_id' => 1,
                'price' => 159,
                'description' => '値上がりしました。',
                'created_at' => '2024-04-16 13:00:00',
                'updated_at' => '2024-04-16 13:00:00',
                'store_id' => $storeId,
                'item_id' => $itemId,
            ],
            [
                'user_id' => 1,
                'price' => 159,
                'description' => '値段は変わりません。',
                'created_at' => '2024-04-17 13:00:00',
                'updated_at' => '2024-04-17 13:00:00',
                'store_id' => $storeId,
                'item_id' => $itemId,
            ],
            [
                'user_id' => 1,
                'price' => 159,
                'description' => '値段は変わりません。',
                'created_at' => '2024-04-18 13:00:00',
                'updated_at' => '2024-04-18 13:00:00',
                'store_id' => $storeId,
                'item_id' => $itemId,
            ],
            [
                'user_id' => 1,
                'price' => 159,
                'description' => '値段は変わりません。',
                'created_at' => '2024-04-19 13:00:00',
                'updated_at' => '2024-04-19 13:00:00',
                'store_id' => $storeId,
                'item_id' => $itemId,
            ],
            [
                'user_id' => 1,
                'price' => 159,
                'description' => '値段は変わりません。',
                'created_at' => '2024-04-20 13:00:00',
                'updated_at' => '2024-04-20 13:00:00',
                'store_id' => $storeId,
                'item_id' => $itemId,
            ],
            [
                'user_id' => 1,
                'price' => 159,
                'description' => '値段は変わりません。',
                'created_at' => '2024-04-21 13:00:00',
                'updated_at' => '2024-04-21 13:00:00',
                'store_id' => $storeId,
                'item_id' => $itemId,
            ],
            [
                'user_id' => 1,
                'price' => 159,
                'description' => '値段は変わりません。',
                'created_at' => '2024-04-22 13:00:00',
                'updated_at' => '2024-04-22 13:00:00',
                'store_id' => $storeId,
                'item_id' => $itemId,
            ],
            [
                'user_id' => 1,
                'price' => 159,
                'description' => '値段は変わりません。',
                'created_at' => '2024-04-23 13:00:00',
                'updated_at' => '2024-04-23 13:00:00',
                'store_id' => $storeId,
                'item_id' => $itemId,
            ],
            [
                'user_id' => 1,
                'price' => 159,
                'description' => '値段は変わりません。',
                'created_at' => '2024-04-24 13:00:00',
                'updated_at' => '2024-04-24 13:00:00',
                'store_id' => $storeId,
                'item_id' => $itemId,
            ],
            [
                'user_id' => 1,
                'price' => 159,
                'description' => '値段は変わりません。',
                'created_at' => '2024-04-25 13:00:00',
                'updated_at' => '2024-04-25 13:00:00',
                'store_id' => $storeId,
                'item_id' => $itemId,
            ],
            [
                'user_id' => 1,
                'price' => 159,
                'description' => '値段は変わりません。',
                'created_at' => '2024-04-26 13:00:00',
                'updated_at' => '2024-04-26 13:00:00',
                'store_id' => $storeId,
                'item_id' => $itemId,
            ],
            [
                'user_id' => 1,
                'price' => 159,
                'description' => '値段は変わりません。',
                'created_at' => '2024-04-27 13:00:00',
                'updated_at' => '2024-04-27 13:00:00',
                'store_id' => $storeId,
                'item_id' => $itemId,
            ],
            [
                'user_id' => 1,
                'price' => 159,
                'description' => '値段は変わりません。',
                'created_at' => '2024-04-28 13:00:00',
                'updated_at' => '2024-04-28 13:00:00',
                'store_id' => $storeId,
                'item_id' => $itemId,
            ],
            [
                'user_id' => 1,
                'price' => 159,
                'description' => '値段は変わりません。',
                'created_at' => '2024-04-29 13:00:00',
                'updated_at' => '2024-04-29 13:00:00',
                'store_id' => $storeId,
                'item_id' => $itemId,
            ],
            [
                'user_id' => 1,
                'price' => 159,
                'description' => '値段は変わりません。',
                'created_at' => '2024-04-30 13:00:00',
                'updated_at' => '2024-04-30 13:00:00',
                'store_id' => $storeId,
                'item_id' => $itemId,
            ],
            [
                'user_id' => 1,
                'price' => 213,
                'description' => '値上がりしています。',
                'created_at' => '2024-05-01 13:00:00',
                'updated_at' => '2024-05-01 13:00:00',
                'store_id' => $storeId,
                'item_id' => $itemId,
            ],
            [
                'user_id' => 1,
                'price' => 213,
                'description' => '値上がりしています。',
                'created_at' => '2024-05-02 13:00:00',
                'updated_at' => '2024-05-02 13:00:00',
                'store_id' => $storeId,
                'item_id' => $itemId,
            ],
            [
                'user_id' => 1,
                'price' => 213,
                'description' => '値上がりしています。',
                'created_at' => '2024-05-03 13:00:00',
                'updated_at' => '2024-05-03 13:00:00',
                'store_id' => $storeId,
                'item_id' => $itemId,
            ],
            [
                'user_id' => 1,
                'price' => 213,
                'description' => '値上がりしています。',
                'created_at' => '2024-05-04 13:00:00',
                'updated_at' => '2024-05-04 13:00:00',
                'store_id' => $storeId,
                'item_id' => $itemId,
            ],
            [
                'user_id' => 1,
                'price' => 213,
                'description' => '値上がりしています。',
                'created_at' => '2024-05-05 13:00:00',
                'updated_at' => '2024-05-05 13:00:00',
                'store_id' => $storeId,
                'item_id' => $itemId,
            ],
            [
                'user_id' => 1,
                'price' => 213,
                'description' => '値上がりしています。',
                'created_at' => '2024-05-06 13:00:00',
                'updated_at' => '2024-05-06 13:00:00',
                'store_id' => $storeId,
                'item_id' => $itemId,
            ],
            [
                'user_id' => 1,
                'price' => 213,
                'description' => '値上がりしています。',
                'created_at' => '2024-05-07 13:00:00',
                'updated_at' => '2024-05-07 13:00:00',
                'store_id' => $storeId,
                'item_id' => $itemId,
            ],
            [
                'user_id' => 1,
                'price' => 213,
                'description' => '値上がりしています。',
                'created_at' => '2024-05-08 13:00:00',
                'updated_at' => '2024-05-08 13:00:00',
                'store_id' => $storeId,
                'item_id' => $itemId,
            ],
            [
                'user_id' => 1,
                'price' => 213,
                'description' => '値上がりしています。',
                'created_at' => '2024-05-09 13:00:00',
                'updated_at' => '2024-05-09 13:00:00',
                'store_id' => $storeId,
                'item_id' => $itemId,
            ],
            [
                'user_id' => 1,
                'price' => 213,
                'description' => '値上がりしています。',
                'created_at' => '2024-05-10 13:00:00',
                'updated_at' => '2024-05-10 13:00:00',
                'store_id' => $storeId,
                'item_id' => $itemId,
            ],
            [
                'user_id' => 1,
                'price' => 213,
                'description' => '値上がりしています。',
                'created_at' => '2024-05-11 13:00:00',
                'updated_at' => '2024-05-11 13:00:00',
                'store_id' => $storeId,
                'item_id' => $itemId,
            ],
            [
                'user_id' => 1,
                'price' => 213,
                'description' => '値上がりしています。',
                'created_at' => '2024-05-12 13:00:00',
                'updated_at' => '2024-05-12 13:00:00',
                'store_id' => $storeId,
                'item_id' => $itemId,
            ],
            [
                'user_id' => 1,
                'price' => 213,
                'description' => '値上がりしています。',
                'created_at' => '2024-05-13 13:00:00',
                'updated_at' => '2024-05-13 13:00:00',
                'store_id' => $storeId,
                'item_id' => $itemId,
            ],
            [
                'user_id' => 1,
                'price' => 213,
                'description' => '値上がりしています。',
                'created_at' => '2024-05-14 13:00:00',
                'updated_at' => '2024-05-14 13:00:00',
                'store_id' => $storeId,
                'item_id' => $itemId,
            ],
            [
                'user_id' => 1,
                'price' => 213,
                'description' => '値上がりしています。',
                'created_at' => '2024-05-15 13:00:00',
                'updated_at' => '2024-05-15 13:00:00',
                'store_id' => $storeId,
                'item_id' => $itemId,
            ],
            [
                'user_id' => 1,
                'price' => 321,
                'description' => 'また値上がりしました。',
                'created_at' => '2024-05-16 13:00:00',
                'updated_at' => '2024-05-16 13:00:00',
                'store_id' => $storeId,
                'item_id' => $itemId,
            ],
            [
                'user_id' => 1,
                'price' => 321,
                'description' => 'また値上がりしました。',
                'created_at' => '2024-05-17 13:00:00',
                'updated_at' => '2024-05-17 13:00:00',
                'store_id' => $storeId,
                'item_id' => $itemId,
            ],
            [
                'user_id' => 1,
                'price' => 321,
                'description' => 'また値上がりしました。',
                'created_at' => '2024-05-18 13:00:00',
                'updated_at' => '2024-05-18 13:00:00',
                'store_id' => $storeId,
                'item_id' => $itemId,
            ],
            [
                'user_id' => 1,
                'price' => 321,
                'description' => '値段は変わりません。',
                'created_at' => '2024-05-19 13:00:00',
                'updated_at' => '2024-05-19 13:00:00',
                'store_id' => $storeId,
                'item_id' => $itemId,
            ],
            [
                'user_id' => 1,
                'price' => 321,
                'description' => '値段は変わりません。',
                'created_at' => '2024-05-20 13:00:00',
                'updated_at' => '2024-05-20 13:00:00',
                'store_id' => $storeId,
                'item_id' => $itemId,
            ],
            [
                'user_id' => 1,
                'price' => 321,
                'description' => '値段は変わりません。',
                'created_at' => '2024-05-21 13:00:00',
                'updated_at' => '2024-05-21 13:00:00',
                'store_id' => $storeId,
                'item_id' => $itemId,
            ],
            [
                'user_id' => 1,
                'price' => 321,
                'description' => '値段は変わりません。',
                'created_at' => '2024-05-22 13:00:00',
                'updated_at' => '2024-05-22 13:00:00',
                'store_id' => $storeId,
                'item_id' => $itemId,
            ],
            [
                'user_id' => 1,
                'price' => 321,
                'description' => '値段は変わりません。',
                'created_at' => '2024-05-23 13:00:00',
                'updated_at' => '2024-05-23 13:00:00',
                'store_id' => $storeId,
                'item_id' => $itemId,
            ],
            [
                'user_id' => 1,
                'price' => 321,
                'description' => '値段は変わりません。',
                'created_at' => '2024-05-24 13:00:00',
                'updated_at' => '2024-05-24 13:00:00',
                'store_id' => $storeId,
                'item_id' => $itemId,
            ],
            [
                'user_id' => 1,
                'price' => 321,
                'description' => '値段は変わりません。',
                'created_at' => '2024-05-25 13:00:00',
                'updated_at' => '2024-05-25 13:00:00',
                'store_id' => $storeId,
                'item_id' => $itemId,
            ],
            [
                'user_id' => 1,
                'price' => 321,
                'description' => '値段は変わりません。',
                'created_at' => '2024-05-26 13:00:00',
                'updated_at' => '2024-05-26 13:00:00',
                'store_id' => $storeId,
                'item_id' => $itemId,
            ],
            [
                'user_id' => 1,
                'price' => 321,
                'description' => '値段は変わりません。',
                'created_at' => '2024-05-27 13:00:00',
                'updated_at' => '2024-05-27 13:00:00',
                'store_id' => $storeId,
                'item_id' => $itemId,
            ],
            [
                'user_id' => 1,
                'price' => 321,
                'description' => '値段は変わりません。',
                'created_at' => '2024-05-28 13:00:00',
                'updated_at' => '2024-05-28 13:00:00',
                'store_id' => $storeId,
                'item_id' => $itemId,
            ],
            [
                'user_id' => 1,
                'price' => 321,
                'description' => '値段は変わりません。',
                'created_at' => '2024-05-29 13:00:00',
                'updated_at' => '2024-05-29 13:00:00',
                'store_id' => $storeId,
                'item_id' => $itemId,
            ],
            [
                'user_id' => 1,
                'price' => 321,
                'description' => '値段は変わりません。',
                'created_at' => '2024-05-30 13:00:00',
                'updated_at' => '2024-05-30 13:00:00',
                'store_id' => $storeId,
                'item_id' => $itemId,
            ],
            [
                'user_id' => 1,
                'price' => 321,
                'description' => '値段は変わりません。',
                'created_at' => '2024-05-31 13:00:00',
                'updated_at' => '2024-05-31 13:00:00',
                'store_id' => $storeId,
                'item_id' => $itemId,
            ],

            [
                'user_id' => 1,
                'price' => 267,
                'description' => 'やすくなりました。',
                'created_at' => '2024-06-01 13:00:00',
                'updated_at' => '2024-06-01 13:00:00',
                'store_id' => $storeId,
                'item_id' => $itemId,
            ],
            [
                'user_id' => 1,
                'price' => 267,
                'description' => '値段は変わりません。',
                'created_at' => '2024-06-02 13:00:00',
                'updated_at' => '2024-06-02 13:00:00',
                'store_id' => $storeId,
                'item_id' => $itemId,
            ],
            [
                'user_id' => 1,
                'price' => 267,
                'description' => '値段は変わりません。',
                'created_at' => '2024-06-03 13:00:00',
                'updated_at' => '2024-06-03 13:00:00',
                'store_id' => $storeId,
                'item_id' => $itemId,
            ],
            [
                'user_id' => 1,
                'price' => 267,
                'description' => '値段は変わりません。',
                'created_at' => '2024-06-04 13:00:00',
                'updated_at' => '2024-06-04 13:00:00',
                'store_id' => $storeId,
                'item_id' => $itemId,
            ],
            [
                'user_id' => 1,
                'price' => 267,
                'description' => '値段は変わりません。',
                'created_at' => '2024-06-05 13:00:00',
                'updated_at' => '2024-06-05 13:00:00',
                'store_id' => $storeId,
                'item_id' => $itemId,
            ],
            [
                'user_id' => 1,
                'price' => 267,
                'description' => '値段は変わりません。',
                'created_at' => '2024-06-06 13:00:00',
                'updated_at' => '2024-06-06 13:00:00',
                'store_id' => $storeId,
                'item_id' => $itemId,
            ],
            [
                'user_id' => 1,
                'price' => 267,
                'description' => '値段は変わりません。',
                'created_at' => '2024-06-07 13:00:00',
                'updated_at' => '2024-06-07 13:00:00',
                'store_id' => $storeId,
                'item_id' => $itemId,
            ],
            [
                'user_id' => 1,
                'price' => 267,
                'description' => '値段は変わりません。',
                'created_at' => '2024-06-08 13:00:00',
                'updated_at' => '2024-06-08 13:00:00',
                'store_id' => $storeId,
                'item_id' => $itemId,
            ],
            [
                'user_id' => 1,
                'price' => 267,
                'description' => '値段は変わりません。',
                'created_at' => '2024-06-09 13:00:00',
                'updated_at' => '2024-06-09 13:00:00',
                'store_id' => $storeId,
                'item_id' => $itemId,
            ],
            [
                'user_id' => 1,
                'price' => 267,
                'description' => '値段は変わりません。',
                'created_at' => '2024-06-10 13:00:00',
                'updated_at' => '2024-06-10 13:00:00',
                'store_id' => $storeId,
                'item_id' => $itemId,
            ],
            [
                'user_id' => 1,
                'price' => 213,
                'description' => '値下がりしました。',
                'created_at' => '2024-06-11 13:00:00',
                'updated_at' => '2024-06-11 13:00:00',
                'store_id' => $storeId,
                'item_id' => $itemId,
            ],
            [
                'user_id' => 1,
                'price' => 213,
                'description' => '値下がりしました。',
                'created_at' => '2024-06-12 13:00:00',
                'updated_at' => '2024-06-12 13:00:00',
                'store_id' => $storeId,
                'item_id' => $itemId,
            ],
            [
                'user_id' => 1,
                'price' => 213,
                'description' => '値下がりしました。',
                'created_at' => '2024-06-13 13:00:00',
                'updated_at' => '2024-06-13 13:00:00',
                'store_id' => $storeId,
                'item_id' => $itemId,
            ],
            [
                'user_id' => 1,
                'price' => 213,
                'description' => '値下がりしました。',
                'created_at' => '2024-06-14 13:00:00',
                'updated_at' => '2024-06-14 13:00:00',
                'store_id' => $storeId,
                'item_id' => $itemId,
            ],
            [
                'user_id' => 1,
                'price' => 213,
                'description' => '値下がりしました。',
                'created_at' => '2024-06-15 13:00:00',
                'updated_at' => '2024-06-15 13:00:00',
                'store_id' => $storeId,
                'item_id' => $itemId,
            ],
            [
                'user_id' => 1,
                'price' => 213,
                'description' => '値下がりしました。',
                'created_at' => '2024-06-16 13:00:00',
                'updated_at' => '2024-06-16 13:00:00',
                'store_id' => $storeId,
                'item_id' => $itemId,
            ],
            [
                'user_id' => 1,
                'price' => 213,
                'description' => '値下がりしました。',
                'created_at' => '2024-06-17 13:00:00',
                'updated_at' => '2024-06-17 13:00:00',
                'store_id' => $storeId,
                'item_id' => $itemId,
            ],
            [
                'user_id' => 1,
                'price' => 213,
                'description' => '値下がりしました。',
                'created_at' => '2024-06-18 13:00:00',
                'updated_at' => '2024-06-18 13:00:00',
                'store_id' => $storeId,
                'item_id' => $itemId,
            ],
            [
                'user_id' => 1,
                'price' => 213,
                'description' => '値下がりしました。',
                'created_at' => '2024-06-19 13:00:00',
                'updated_at' => '2024-06-19 13:00:00',
                'store_id' => $storeId,
                'item_id' => $itemId,
            ],
            [
                'user_id' => 1,
                'price' => 213,
                'description' => '値下がりしました。',
                'created_at' => '2024-06-20 13:00:00',
                'updated_at' => '2024-06-20 13:00:00',
                'store_id' => $storeId,
                'item_id' => $itemId,
            ],
            [
                'user_id' => 1,
                'price' => 267,
                'description' => '値上がりしました。',
                'created_at' => '2024-06-21 13:00:00',
                'updated_at' => '2024-06-21 13:00:00',
                'store_id' => $storeId,
                'item_id' => $itemId,
            ],
            [
                'user_id' => 1,
                'price' => 267,
                'description' => '値上がりしました。',
                'created_at' => '2024-06-22 13:00:00',
                'updated_at' => '2024-06-22 13:00:00',
                'store_id' => $storeId,
                'item_id' => $itemId,
            ],
            [
                'user_id' => 1,
                'price' => 267,
                'description' => '値上がりしました。',
                'created_at' => '2024-06-23 13:00:00',
                'updated_at' => '2024-06-23 13:00:00',
                'store_id' => $storeId,
                'item_id' => $itemId,
            ],
            [
                'user_id' => 1,
                'price' => 267,
                'description' => '値上がりしました。',
                'created_at' => '2024-06-24 13:00:00',
                'updated_at' => '2024-06-24 13:00:00',
                'store_id' => $storeId,
                'item_id' => $itemId,
            ],
            [
                'user_id' => 1,
                'price' => 267,
                'description' => '値上がりしました。',
                'created_at' => '2024-06-25 13:00:00',
                'updated_at' => '2024-06-25 13:00:00',
                'store_id' => $storeId,
                'item_id' => $itemId,
            ],
            [
                'user_id' => 1,
                'price' => 267,
                'description' => '値段は変わりません。',
                'created_at' => '2024-06-26 13:00:00',
                'updated_at' => '2024-06-26 13:00:00',
                'store_id' => $storeId,
                'item_id' => $itemId,
            ],
            [
                'user_id' => 1,
                'price' => 267,
                'description' => '値段は変わりません。',
                'created_at' => '2024-06-27 13:00:00',
                'updated_at' => '2024-06-27 13:00:00',
                'store_id' => $storeId,
                'item_id' => $itemId,
            ],
            [
                'user_id' => 1,
                'price' => 267,
                'description' => '値段は変わりません。',
                'created_at' => '2024-06-28 13:00:00',
                'updated_at' => '2024-06-28 13:00:00',
                'store_id' => $storeId,
                'item_id' => $itemId,
            ],
            [
                'user_id' => 1,
                'price' => 267,
                'description' => '値段は変わりません。',
                'created_at' => '2024-06-29 13:00:00',
                'updated_at' => '2024-06-29 13:00:00',
                'store_id' => $storeId,
                'item_id' => $itemId,
            ],
            [
                'user_id' => 1,
                'price' => 267,
                'description' => '値段は変わりません。',
                'created_at' => '2024-06-30 13:00:00',
                'updated_at' => '2024-06-30 13:00:00',
                'store_id' => $storeId,
                'item_id' => $itemId,
            ],
        ]);
    }
}
