<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class postSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $storeId = 7;
        $itemId= 1;
        DB::table('posts')->insert([
            [
                'user_id' => 1,
                'price' => 88,
                'description' => '安いです。',
                'created_at' => '2023-01-01 13:00:00',
                'updated_at' => '2023-01-01 13:00:00',
                'store_id' => $storeId,
                'item_id' => $itemId,
            ],
            [
                'user_id' => 1,
                'price' => 88,
                'description' => '安いです。',
                'created_at' => '2023-01-11 13:00:00',
                'updated_at' => '2023-01-11 13:00:00',
                'store_id' => $storeId,
                'item_id' => $itemId,
            ],
            [
                'user_id' => 1,
                'price' => 98,
                'description' => '安いです。',
                'created_at' => '2023-01-21 13:00:00',
                'updated_at' => '2023-01-21 13:00:00',
                'store_id' => $storeId,
                'item_id' => $itemId,
            ],
            [
                'user_id' => 1,
                'price' => 98,
                'description' => '安いです。',
                'created_at' => '2023-01-31 13:00:00',
                'updated_at' => '2023-01-31 13:00:00',
                'store_id' => $storeId,
                'item_id' => $itemId,
            ],
            [
                'user_id' => 1,
                'price' => 108,
                'description' => '安いです。',
                'created_at' => '2023-02-01 13:00:00',
                'updated_at' => '2023-02-01 13:00:00',
                'store_id' => $storeId,
                'item_id' => $itemId,
            ],
            [
                'user_id' => 1,
                'price' => 108,
                'description' => '安いです。',
                'created_at' => '2023-02-11 13:00:00',
                'updated_at' => '2023-02-11 13:00:00',
                'store_id' => $storeId,
                'item_id' => $itemId,
            ],
            [
                'user_id' => 1,
                'price' => 98,
                'description' => '安いです。',
                'created_at' => '2023-02-21 13:00:00',
                'updated_at' => '2023-02-21 13:00:00',
                'store_id' => $storeId,
                'item_id' => $itemId,
            ],
            [
                'user_id' => 1,
                'price' => 98,
                'description' => '安いです。',
                'created_at' => '2023-03-01 13:00:00',
                'updated_at' => '2023-03-01 13:00:00',
                'store_id' => $storeId,
                'item_id' => $itemId,
            ],
            [
                'user_id' => 1,
                'price' => 88,
                'description' => '安いです。',
                'created_at' => '2023-03-11 13:00:00',
                'updated_at' => '2023-03-11 13:00:00',
                'store_id' => $storeId,
                'item_id' => $itemId,
            ],
            [
                'user_id' => 1,
                'price' => 88,
                'description' => '安いです。',
                'created_at' => '2023-03-21 13:00:00',
                'updated_at' => '2023-03-21 13:00:00',
                'store_id' => $storeId,
                'item_id' => $itemId,
            ],
            [
                'user_id' => 1,
                'price' => 98,
                'description' => '安いです。',
                'created_at' => '2023-03-30 13:00:00',
                'updated_at' => '2023-03-30 13:00:00',
                'store_id' => $storeId,
                'item_id' => $itemId,
            ],
            [
                'user_id' => 1,
                'price' => 108,
                'description' => '安いです。',
                'created_at' => '2023-04-01 13:00:00',
                'updated_at' => '2023-04-01 13:00:00',
                'store_id' => $storeId,
                'item_id' => $itemId,
            ],
            [
                'user_id' => 1,
                'price' => 98,
                'description' => '安いです。',
                'created_at' => '2023-04-11 13:00:00',
                'updated_at' => '2023-04-11 13:00:00',
                'store_id' => $storeId,
                'item_id' => $itemId,
            ],
            [
                'user_id' => 1,
                'price' => 98,
                'description' => '安いです。',
                'created_at' => '2023-04-21 13:00:00',
                'updated_at' => '2023-04-21 13:00:00',
                'store_id' => $storeId,
                'item_id' => $itemId,
            ],
            [
                'user_id' => 1,
                'price' => 108,
                'description' => '安いです。',
                'created_at' => '2023-05-01 13:00:00',
                'updated_at' => '2023-05-01 13:00:00',
                'store_id' => $storeId,
                'item_id' => $itemId,
            ],
            [
                'user_id' => 1,
                'price' => 108,
                'description' => '安いです。',
                'created_at' => '2023-05-11 13:00:00',
                'updated_at' => '2023-05-11 13:00:00',
                'store_id' => $storeId,
                'item_id' => $itemId,
            ],
            [
                'user_id' => 1,
                'price' => 118,
                'description' => '安いです。',
                'created_at' => '2023-05-21 13:00:00',
                'updated_at' => '2023-05-21 13:00:00',
                'store_id' => $storeId,
                'item_id' => $itemId,
            ],
            [
                'user_id' => 1,
                'price' => 108,
                'description' => '値上がりしました。',
                'created_at' => '2023-05-31 13:00:00',
                'updated_at' => '2023-05-31 13:00:00',
                'store_id' => $storeId,
                'item_id' => $itemId,
            ],
            [
                'user_id' => 1,
                'price' => 118,
                'description' => '値段は変わりません。',
                'created_at' => '2023-06-01 13:00:00',
                'updated_at' => '2023-06-01 13:00:00',
                'store_id' => $storeId,
                'item_id' => $itemId,
            ],
            [
                'user_id' => 1,
                'price' => 108,
                'description' => '安いです。',
                'created_at' => '2023-06-11 13:00:00',
                'updated_at' => '2023-06-11 13:00:00',
                'store_id' => $storeId,
                'item_id' => $itemId,
            ],
            [
                'user_id' => 1,
                'price' => 98,
                'description' => '安いです。',
                'created_at' => '2023-06-21 13:00:00',
                'updated_at' => '2023-06-21 13:00:00',
                'store_id' => $storeId,
                'item_id' => $itemId,
            ],
            [
                'user_id' => 1,
                'price' => 98,
                'description' => '安いです。',
                'created_at' => '2023-07-01 13:00:00',
                'updated_at' => '2023-07-01 13:00:00',
                'store_id' => $storeId,
                'item_id' => $itemId,
            ],
            [
                'user_id' => 1,
                'price' => 108,
                'description' => '値上がりしました。',
                'created_at' => '2023-07-11 13:00:00',
                'updated_at' => '2023-07-11 13:00:00',
                'store_id' => $storeId,
                'item_id' => $itemId,
            ],
            [
                'user_id' => 1,
                'price' => 98,
                'description' => '値上がりしました。',
                'created_at' => '2023-07-21 13:00:00',
                'updated_at' => '2023-07-21 13:00:00',
                'store_id' => $storeId,
                'item_id' => $itemId,
            ],
            [
                'user_id' => 1,
                'price' => 118,
                'description' => '値上がりしました。',
                'created_at' => '2023-07-31 13:00:00',
                'updated_at' => '2023-07-31 13:00:00',
                'store_id' => $storeId,
                'item_id' => $itemId,
            ],
            [
                'user_id' => 1,
                'price' => 118,
                'description' => '少し値下がりしました。',
                'created_at' => '2023-08-01 13:00:00',
                'updated_at' => '2023-08-01 13:00:00',
                'store_id' => $storeId,
                'item_id' => $itemId,
            ],
            [
                'user_id' => 1,
                'price' => 128,
                'description' => '値段は変わりません。',
                'created_at' => '2023-08-11 13:00:00',
                'updated_at' => '2023-08-11 13:00:00',
                'store_id' => $storeId,
                'item_id' => $itemId,
            ],
            [
                'user_id' => 1,
                'price' => 128,
                'description' => '値上がりしました。',
                'created_at' => '2023-08-21 13:00:00',
                'updated_at' => '2023-08-21 13:00:00',
                'store_id' => $storeId,
                'item_id' => $itemId,
            ],
            [
                'user_id' => 1,
                'price' => 128,
                'description' => '値段は変わりません。',
                'created_at' => '2023-08-31 13:00:00',
                'updated_at' => '2023-08-31 13:00:00',
                'store_id' => $storeId,
                'item_id' => $itemId,
            ],
            [
                'user_id' => 1,
                'price' => 128,
                'description' => '値上がりしました。',
                'created_at' => '2023-09-01 13:00:00',
                'updated_at' => '2023-09-01 13:00:00',
                'store_id' => $storeId,
                'item_id' => $itemId,
            ],
            [
                'user_id' => 1,
                'price' => 108,
                'description' => '値上がりしました。',
                'created_at' => '2023-09-11 13:00:00',
                'updated_at' => '2023-09-11 13:00:00',
                'store_id' => $storeId,
                'item_id' => $itemId,
            ],
            [
                'user_id' => 1,
                'price' => 108,
                'description' => '値下がりしました。',
                'created_at' => '2023-09-21 13:00:00',
                'updated_at' => '2023-09-21 13:00:00',
                'store_id' => $storeId,
                'item_id' => $itemId,
            ],
            [
                'user_id' => 1,
                'price' => 108,
                'description' => '変わりません。',
                'created_at' => '2023-10-01 13:00:00',
                'updated_at' => '2023-10-01 13:00:00',
                'store_id' => $storeId,
                'item_id' => $itemId,
            ],
            [
                'user_id' => 1,
                'price' => 118,
                'description' => '値上がりしています。',
                'created_at' => '2023-10-11 13:00:00',
                'updated_at' => '2023-10-11 13:00:00',
                'store_id' => $storeId,
                'item_id' => $itemId,
            ],
            [
                'user_id' => 1,
                'price' => 118,
                'description' => '値上がりしています。',
                'created_at' => '2023-10-21 13:00:00',
                'updated_at' => '2023-10-21 13:00:00',
                'store_id' => $storeId,
                'item_id' => $itemId,
            ],
            [
                'user_id' => 1,
                'price' => 128,
                'description' => '下がりました。',
                'created_at' => '2023-10-31 13:00:00',
                'updated_at' => '2023-10-31 13:00:00',
                'store_id' => $storeId,
                'item_id' => $itemId,
            ],
            [
                'user_id' => 1,
                'price' => 118,
                'description' => '値上がりしています。',
                'created_at' => '2023-11-01 13:00:00',
                'updated_at' => '2023-11-01 13:00:00',
                'store_id' => $storeId,
                'item_id' => $itemId,
            ],
            [
                'user_id' => 1,
                'price' => 128,
                'description' => '値上がりしています。',
                'created_at' => '2023-11-11 13:00:00',
                'updated_at' => '2023-11-11 13:00:00',
                'store_id' => $storeId,
                'item_id' => $itemId,
            ],
            [
                'user_id' => 1,
                'price' => 128,
                'description' => '値上がりしています。',
                'created_at' => '2023-11-21 13:00:00',
                'updated_at' => '2023-11-21 13:00:00',
                'store_id' => $storeId,
                'item_id' => $itemId,
            ],
            [
                'user_id' => 1,
                'price' => 128,
                'description' => '値上がりしています。',
                'created_at' => '2023-12-01 13:00:00',
                'updated_at' => '2023-12-01 13:00:00',
                'store_id' => $storeId,
                'item_id' => $itemId,
            ],
            [
                'user_id' => 1,
                'price' => 108,
                'description' => '下がりました。',
                'created_at' => '2023-12-11 13:00:00',
                'updated_at' => '2023-12-11 13:00:00',
                'store_id' => $storeId,
                'item_id' => $itemId,
            ],
            [
                'user_id' => 1,
                'price' => 108,
                'description' => '下がりました。',
                'created_at' => '2023-12-21 13:00:00',
                'updated_at' => '2023-12-21 13:00:00',
                'store_id' => $storeId,
                'item_id' => $itemId,
            ],
            [
                'user_id' => 1,
                'price' => 118,
                'description' => '値上がりしています。',
                'created_at' => '2023-12-31 13:00:00',
                'updated_at' => '2023-12-31 13:00:00',
                'store_id' => $storeId,
                'item_id' => $itemId,
            ],
            [
                'user_id' => 1,
                'price' => 118,
                'description' => '上がりました。',
                'created_at' => '2024-01-01 13:00:00',
                'updated_at' => '2024-01-01 13:00:00',
                'store_id' => $storeId,
                'item_id' => $itemId,
            ],
            [
                'user_id' => 1,
                'price' => 118,
                'description' => '下がりました。',
                'created_at' => '2024-01-11 13:00:00',
                'updated_at' => '2024-01-11 13:00:00',
                'store_id' => $storeId,
                'item_id' => $itemId,
            ],
            [
                'user_id' => 1,
                'price' => 128,
                'description' => '変わりません。',
                'created_at' => '2024-01-21 13:00:00',
                'updated_at' => '2024-01-21 13:00:00',
                'store_id' => $storeId,
                'item_id' => $itemId,
            ],
            [
                'user_id' => 1,
                'price' => 128,
                'description' => '下がりました。',
                'created_at' => '2024-01-31 13:00:00',
                'updated_at' => '2024-01-31 13:00:00',
                'store_id' => $storeId,
                'item_id' => $itemId,
            ],
            [
                'user_id' => 1,
                'price' => 128,
                'description' => '値上がりしています。',
                'created_at' => '2024-02-01 13:00:00',
                'updated_at' => '2024-02-01 13:00:00',
                'store_id' => $storeId,
                'item_id' => $itemId,
            ],
            [
                'user_id' => 1,
                'price' => 128,
                'description' => '値上がりしています。',
                'created_at' => '2024-02-11 13:00:00',
                'updated_at' => '2024-02-11 13:00:00',
                'store_id' => $storeId,
                'item_id' => $itemId,
            ],
            [
                'user_id' => 1,
                'price' => 128,
                'description' => 'また値上がりしました。',
                'created_at' => '2024-02-21 13:00:00',
                'updated_at' => '2024-02-21 13:00:00',
                'store_id' => $storeId,
                'item_id' => $itemId,
            ],
            [
                'user_id' => 1,
                'price' => 128,
                'description' => 'また値上がりしました。',
                'created_at' => '2024-03-01 13:00:00',
                'updated_at' => '2024-03-01 13:00:00',
                'store_id' => $storeId,
                'item_id' => $itemId,
            ],
            [
                'user_id' => 1,
                'price' => 148,
                'description' => 'また値上がりしました。',
                'created_at' => '2024-03-11 13:00:00',
                'updated_at' => '2024-03-11 13:00:00',
                'store_id' => $storeId,
                'item_id' => $itemId,
            ],
            [
                'user_id' => 1,
                'price' => 148,
                'description' => '値段は変わりません。',
                'created_at' => '2024-03-21 13:00:00',
                'updated_at' => '2024-03-21 13:00:00',
                'store_id' => $storeId,
                'item_id' => $itemId,
            ],
            [
                'user_id' => 1,
                'price' => 148,
                'description' => 'また値上がりしました。',
                'created_at' => '2024-03-31 13:00:00',
                'updated_at' => '2024-03-31 13:00:00',
                'store_id' => $storeId,
                'item_id' => $itemId,
            ],
        ]);
    }
}
