<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class postSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $storeId = 8;
        $itemId= 1;
        DB::table('posts')->insert([
            [
                'user_id' => 1,
                'price' => 108,
                'description' => '安いです。',
                'created_at' => '2023-01-05 13:00:00',
                'updated_at' => '2023-01-05 13:00:00',
                'store_id' => $storeId,
                'item_id' => $itemId,
            ],
            [
                'user_id' => 1,
                'price' => 108,
                'description' => '安いです。',
                'created_at' => '2023-01-25 13:00:00',
                'updated_at' => '2023-01-25 13:00:00',
                'store_id' => $storeId,
                'item_id' => $itemId,
            ],
            [
                'user_id' => 1,
                'price' => 118,
                'description' => '安いです。',
                'created_at' => '2023-02-05 13:00:00',
                'updated_at' => '2023-02-05 13:00:00',
                'store_id' => $storeId,
                'item_id' => $itemId,
            ],
            [
                'user_id' => 1,
                'price' => 118,
                'description' => '安いです。',
                'created_at' => '2023-02-25 13:00:00',
                'updated_at' => '2023-02-25 13:00:00',
                'store_id' => $storeId,
                'item_id' => $itemId,
            ],
            [
                'user_id' => 1,
                'price' => 128,
                'description' => '安いです。',
                'created_at' => '2023-03-05 13:00:00',
                'updated_at' => '2023-03-05 13:00:00',
                'store_id' => $storeId,
                'item_id' => $itemId,
            ],
            [
                'user_id' => 1,
                'price' => 128,
                'description' => '安いです。',
                'created_at' => '2023-03-25 13:00:00',
                'updated_at' => '2023-03-25 13:00:00',
                'store_id' => $storeId,
                'item_id' => $itemId,
            ],
            [
                'user_id' => 1,
                'price' => 118,
                'description' => '安いです。',
                'created_at' => '2023-04-05 13:00:00',
                'updated_at' => '2023-04-05 13:00:00',
                'store_id' => $storeId,
                'item_id' => $itemId,
            ],
            [
                'user_id' => 1,
                'price' => 118,
                'description' => '安いです。',
                'created_at' => '2023-04-25 13:00:00',
                'updated_at' => '2023-04-25 13:00:00',
                'store_id' => $storeId,
                'item_id' => $itemId,
            ],
            [
                'user_id' => 1,
                'price' => 128,
                'description' => '安いです。',
                'created_at' => '2023-05-05 13:00:00',
                'updated_at' => '2023-05-05 13:00:00',
                'store_id' => $storeId,
                'item_id' => $itemId,
            ],
            [
                'user_id' => 1,
                'price' => 128,
                'description' => '安いです。',
                'created_at' => '2023-05-25 13:00:00',
                'updated_at' => '2023-05-25 13:00:00',
                'store_id' => $storeId,
                'item_id' => $itemId,
            ],
            [
                'user_id' => 1,
                'price' => 138,
                'description' => '安いです。',
                'created_at' => '2023-06-05 13:00:00',
                'updated_at' => '2023-06-05 13:00:00',
                'store_id' => $storeId,
                'item_id' => $itemId,
            ],
            [
                'user_id' => 1,
                'price' => 138,
                'description' => '安いです。',
                'created_at' => '2023-06-25 13:00:00',
                'updated_at' => '2023-06-25 13:00:00',
                'store_id' => $storeId,
                'item_id' => $itemId,
            ],
            [
                'user_id' => 1,
                'price' => 128,
                'description' => '安いです。',
                'created_at' => '2023-07-05 13:00:00',
                'updated_at' => '2023-07-05 13:00:00',
                'store_id' => $storeId,
                'item_id' => $itemId,
            ],
            [
                'user_id' => 1,
                'price' => 128,
                'description' => '安いです。',
                'created_at' => '2023-07-25 13:00:00',
                'updated_at' => '2023-07-25 13:00:00',
                'store_id' => $storeId,
                'item_id' => $itemId,
            ],
            [
                'user_id' => 1,
                'price' => 138,
                'description' => '安いです。',
                'created_at' => '2023-08-05 13:00:00',
                'updated_at' => '2023-08-05 13:00:00',
                'store_id' => $storeId,
                'item_id' => $itemId,
            ],
            [
                'user_id' => 1,
                'price' => 148,
                'description' => '安いです。',
                'created_at' => '2023-08-25 13:00:00',
                'updated_at' => '2023-08-25 13:00:00',
                'store_id' => $storeId,
                'item_id' => $itemId,
            ],
            [
                'user_id' => 1,
                'price' => 148,
                'description' => '値上がりしました。',
                'created_at' => '2023-09-05 13:00:00',
                'updated_at' => '2023-09-05 13:00:00',
                'store_id' => $storeId,
                'item_id' => $itemId,
            ],
            [
                'user_id' => 1,
                'price' => 138,
                'description' => '値段は変わりません。',
                'created_at' => '2023-09-25 13:00:00',
                'updated_at' => '2023-09-25 13:00:00',
                'store_id' => $storeId,
                'item_id' => $itemId,
            ],
            [
                'user_id' => 1,
                'price' => 138,
                'description' => '安いです。',
                'created_at' => '2023-10-05 13:00:00',
                'updated_at' => '2023-10-05 13:00:00',
                'store_id' => $storeId,
                'item_id' => $itemId,
            ],
            [
                'user_id' => 1,
                'price' => 148,
                'description' => '安いです。',
                'created_at' => '2023-10-25 13:00:00',
                'updated_at' => '2023-10-25 13:00:00',
                'store_id' => $storeId,
                'item_id' => $itemId,
            ],
            [
                'user_id' => 1,
                'price' => 148,
                'description' => '安いです。',
                'created_at' => '2023-11-05 13:00:00',
                'updated_at' => '2023-11-05 13:00:00',
                'store_id' => $storeId,
                'item_id' => $itemId,
            ],
            [
                'user_id' => 1,
                'price' => 158,
                'description' => '値上がりしました。',
                'created_at' => '2023-11-25 13:00:00',
                'updated_at' => '2023-11-25 13:00:00',
                'store_id' => $storeId,
                'item_id' => $itemId,
            ],
            [
                'user_id' => 1,
                'price' => 158,
                'description' => '値上がりしました。',
                'created_at' => '2023-12-05 13:00:00',
                'updated_at' => '2023-12-05 13:00:00',
                'store_id' => $storeId,
                'item_id' => $itemId,
            ],
            [
                'user_id' => 1,
                'price' => 148,
                'description' => '値上がりしました。',
                'created_at' => '2023-12-25 13:00:00',
                'updated_at' => '2023-12-25 13:00:00',
                'store_id' => $storeId,
                'item_id' => $itemId,
            ],
            [
                'user_id' => 1,
                'price' => 148,
                'description' => '少し値下がりしました。',
                'created_at' => '2024-01-05 13:00:00',
                'updated_at' => '2024-01-05 13:00:00',
                'store_id' => $storeId,
                'item_id' => $itemId,
            ],
            [
                'user_id' => 1,
                'price' => 158,
                'description' => '値段は変わりません。',
                'created_at' => '2024-01-25 13:00:00',
                'updated_at' => '2024-01-25 13:00:00',
                'store_id' => $storeId,
                'item_id' => $itemId,
            ],
            [
                'user_id' => 1,
                'price' => 148,
                'description' => '値上がりしました。',
                'created_at' => '2024-02-05 13:00:00',
                'updated_at' => '2024-02-05 13:00:00',
                'store_id' => $storeId,
                'item_id' => $itemId,
            ],
            [
                'user_id' => 1,
                'price' => 158,
                'description' => '値段は変わりません。',
                'created_at' => '2024-02-25 13:00:00',
                'updated_at' => '2024-02-25 13:00:00',
                'store_id' => $storeId,
                'item_id' => $itemId,
            ],
            [
                'user_id' => 1,
                'price' => 168,
                'description' => '値上がりしました。',
                'created_at' => '2024-03-05 13:00:00',
                'updated_at' => '2024-03-05 13:00:00',
                'store_id' => $storeId,
                'item_id' => $itemId,
            ],
            [
                'user_id' => 1,
                'price' => 158,
                'description' => '値上がりしました。',
                'created_at' => '2024-03-25 13:00:00',
                'updated_at' => '2024-03-25 13:00:00',
                'store_id' => $storeId,
                'item_id' => $itemId,
            ],
            [
                'user_id' => 1,
                'price' => 168,
               'description' => '値上がりしています。',
                'created_at' => '2024-04-05 13:00:00',
                'updated_at' => '2024-04-05 13:00:00',
                'store_id' => $storeId,
                'item_id' => $itemId,
            ],
            [
                'user_id' => 1,
                'price' => 188,
                'description' => '値上がりしています。',
                'created_at' => '2024-04-15 13:00:00',
                'updated_at' => '2024-04-15 13:00:00',
                'store_id' => $storeId,
                'item_id' => $itemId,
            ],
            [
                'user_id' => 1,
                'price' => 208,
                'description' => '値上がりしています。',
                'created_at' => '2024-05-05 13:00:00',
                'updated_at' => '2024-05-05 13:00:00',
                'store_id' => $storeId,
                'item_id' => $itemId,
            ],
            [
                'user_id' => 1,
                'price' => 248,
                'description' => '値上がりしています。',
                'created_at' => '2024-05-15 13:00:00',
                'updated_at' => '2024-05-15 13:00:00',
                'store_id' => $storeId,
                'item_id' => $itemId,
            ],
            [
                'user_id' => 1,
                'price' => 268,
                'description' => '値上がりしています。',
                'created_at' => '2024-06-05 13:00:00',
                'updated_at' => '2024-06-05 13:00:00',
                'store_id' => $storeId,
                'item_id' => $itemId,
            ],
            [
                'user_id' => 1,
                'price' => 288,
                'description' => '値上がりしています。',
                'created_at' => '2024-06-15 13:00:00',
                'updated_at' => '2024-06-15 13:00:00',
                'store_id' => $storeId,
                'item_id' => $itemId,
            ],
            [
                'user_id' => 1,
                'price' => 308,
                'description' => '値上がりしています。',
                'created_at' => '2024-07-05 13:00:00',
                'updated_at' => '2024-07-05 13:00:00',
                'store_id' => $storeId,
                'item_id' => $itemId,
            ]
        ]);
    }
}
